### ISSUE TITLE
Stopped communicating with Homey and can't include anymore

### ISSUE THREAD

**Issue by JaNeiJohan** [TedTolboom/no.IDLock#27] opened 2019-11-24 17:25 UTC
Hi
My ID Lock 150 suddenly stopped communicating with Homey yesterday. I have tried all the tricks around, but can’t get it to work again. Then tried excluding it from Homey and re-include.
-Success excluding from Homey, but NO success including again. 
What i’v tried so far:
-Reinstalling ID Lock App - Then tried to include again with NO success
-Restarting Homey - Then tried to include again with NO success
-Reset ID Lock 150 and 3 x reset ZWave module - Then tried to include again with NO success

To verify if the ZWave modul was working, i tried to add it to my other ZWave hub (FutureHome). I had no problem including the device here. Everything working fine, so i’v concluded that it cant be a faulty ZWave-modul.

Finally tried again several times more to include in Homey, but still no success.

Homey v3.1.0
Id lock v1.4.49
Z wave module 01B/v1.6 

(Diagnostic:
f9c75256-a1fc-412b-aa58-58b267334479)

**Comment by JaNeiJohan** [comment] 2019-11-25 16:30
I'v opened a support-case with my supplier of z-lock/zwave. They will run a few tests on a in-house Homey system of their own. 
Will update this tread if necessary...

**Comment by JaNeiJohan** [comment] 2019-11-26 12:49
Ok, my supplier and ID Lock have now replicated and tested my problem. They confirmed to me that the issue is related to Homey update v3.1.0.
They have reported the problem to Athom/Homey. Lets hope they fix this soon!

**Comment by JaNeiJohan** [comment] 2019-11-27 21:17
My Homey log from IDLock fail inclusion, attached
[My Homey_log_Add_Excl.txt](https://github.com/TedTolboom/no.IDLock/files/3898808/My.Homey_log_Add_Excl.txt)

**Comment by TedTolboom** [comment] 2019-11-28 08:24
Thanks for sharing...

Just checking...
Your tried to include, ending up in status.already_added

Can you try the following:
1. Move Homey towards close proximity of the ID lock and wait until fully booted (~30 minutes)
2. Enable Z-wave logging at https://developer.athom.com/tools/zwave
3. Go to settings > Z-wave > remove a node and set the ID lock into exclusion mode (according to the manual)
3. Reset the ID lock to factory defaults (according to the manual)
4. Remove batteries for 5 minutes and then try to include the ID lock

And share the Z-wave log afterwards

**Comment by JaNeiJohan** [comment] 2019-11-28 09:24
> 4. Reset the ID lock to factory defaults (according to the manual)
Do you mean the ZWave module or the ID Lock it self (or both)?

**Comment by JaNeiJohan** [comment] 2019-11-28 22:23
Hi Ted
I just tried what your procedure and here is the log: 
[My Homey_log2_Excl_Res_Batt.txt](https://github.com/TedTolboom/no.IDLock/files/3903108/My.Homey_log2_Excl_Res_Batt.txt)

1. Moved Homey to close proximity of the ID lock and wait until fully booted (~30 minutes)
2...
3. Excluded ID Lock
4. Factory reset ID Lock ZWave
5. Batteries out for 5 mins - Then tried to include , but fail with “_No Z-Wave device found_” in the app.

(6. Tried to include yet again, and get “_status.already.added_” in the app.)
(7. Successfully excluded ID Lock from >settings > Z-wave > remove a device)
...
It´s all in the log ;)

At the end i did a new factory reset of ID Lock ZWave and removed the module until next time (or fix)...

Appreciate your effort trying to solve this 👍

**Comment by JaNeiJohan** [comment] 2019-12-01 15:13
Hi Ted
Did you get a chance to look into this after i sent you the last log-file?

**Comment by Marlark** [comment] 2019-12-05 15:13
Hi Ted

I am having the same issue as above so im adding some additional things for you in term of log and so on. I took out a zwave log from when i tried to include and got same error like above.
[idlock inclusion log.txt](https://github.com/TedTolboom/no.IDLock/files/3927569/idlock.inclusion.log.txt)

I hope it helps you Ted i also sent a app diag in a pm for you from when i actualy managed to add the unit but nothing worked in term of actualy talking to the unit or getting event data from the unit to the app.

**Comment by torroa** [comment] 2019-12-05 20:25
Same issue here: "No device found"

**Comment by Marlark** [comment] 2019-12-06 13:35
I updated to 3.2.0 rc3 today and tried to unclude my lock. and something else changed. before i only got one page on how to include and then then i do that it failes with no device. but now.... I get two green buttons and where it want to first exclude a lock and secodly when i have done a exclusion it check mark the first green and then moves over to a inclusion text. the lock behaves a lite dig on inclusion when i have done it i get one of those bell sounds that say ok it went good. but the app get a text that first flash by that i dont get to read and then a something went wrong error message when adding the device.

**Comment by torroa** [comment] 2019-12-10 12:08
Any chance that this is fixed with Homey v3.2 ?

**Comment by Marlark** [comment] 2019-12-10 12:23
I just updated mine to 3.2.0. So i will try it again in a moment. It need a moment to get the z-wave network to settle first.

**Comment by torroa** [comment] 2019-12-10 17:45
Nah, didn't work here. Just get an error message saying something went wrong.... basically telling; you should have brought a propper hub..

**Comment by JaNeiJohan** [comment] 2019-12-11 13:57
Bump @TedTolboom

**Comment by Marlark** [comment] 2019-12-12 18:28
There is a rc release for fixing the walli. lets see if it helps us in any way.

**Comment by erlingtei** [comment] 2019-12-15 01:33
The user prj_84 has in the [Slack thread](https://athomcommunity.slack.com/archives/C04E9KJAD/p1576158094383800) confirmed that he can add the lock in version 3.2.1-rc.2, but he writes: 
Idlock can now be added om with latest beta firmware. **Though it will not function. Not possible to lock/unlock. No atributes is sent.**
@TedTolboom

**Comment by TedTolboom** [comment] 2019-12-19 21:19
Guys, apologies for providing an update so late. I am lacking the free time recently to actively address all topics in a proper manner.

Brief update on the inclusion issue with the IDLock based on a recent 3.x release.

Based on the logging you provided, the cause of the problem of not being able to include the IDLock has been determined.
In one of the 3.x releases, Athom added a command to the inclusion sequence to request the firmware version of the interviewed device.
The response that the IDLock sends, is addressed to the wrong nodeID and therefore ignored by Homey, which results in a timeout of the inclusion process.

I’m in contact with both Athom and IDLock to get this issue resolved, since it is outside of my control from app space. Likely, it will require an update from either one of them.

**Comment by ugle1** [comment] 2019-12-19 21:33
Thanks for looking into it @TedTolboom. It's clarifying and sobering to know that both idlock and athom needs to do some work.

**Comment by JaNeiJohan** [comment] 2019-12-19 21:35
Ok @TedTolboom 
Thanks for the update, and many thanks for your app contribution's :)

Awaiting fix from Athom/IDLock then...

**Comment by Marlark** [comment] 2020-01-09 17:30
I can confirm that it works now with rc7 version. Thx Ted for your work on this with Athom.

**Comment by ugle1** [comment] 2020-01-09 17:49
And rc8! First attempt failed though. On second inclusion everything was
OK. Thanks TED!

tor. 9. jan. 2020, 18:30 skrev Marlark <notifications@github.com>:

**Comment by Marlark** [comment] 2020-01-09 18:10
Added rc8 after inclusion. Everything stil work but i had it included on rc7.

**Comment by JaNeiJohan** [comment] 2020-09-23 09:13
Homey issue fixed

**Closed** 2020-09-23 09:13 UTC

**Comment by Tekvi** [comment] 2022-01-24 22:12
Getting the same problem as described in this thread, not being able to connect id lock 150 z-wave to Homey. Have Homey version 7.2.1 and latest version from the id lock updater installed. Are able to get the first green checkbox, but then an error message due to time out. Any tips?

**Comment by Marlark** [comment] 2022-01-25 12:31
You havet tog do inclusion 2 Times and do them quick because the incl will timeout if you take to long om the second one.

Hämta Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by patchie** [comment] 2023-11-08 20:52
Please update the inclusion page to say that you need to do the inclusion steps on the idlock 2 times in a row. One time for each number icon in the top.
